name: segmenteveryforam

channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - matplotlib
      - scipy
      - pillow
      - scikit-image
      - scikit-learn
      - pandas
      - geopandas
      - tqdm
      - networkx
      - shapely
      - rasterio
      - opencv-python
      - rtree
      - tensorflow
      - keras
      - torch
      - torchvision
      - sam2
      - PyQt5
      - charset-normalizer
      - jupyterlab
      - -e .